### PR TITLE
Fixes table formatting issue

### PR DESCRIPTION
**Pull request by rajadilipkolli**
Currently table is distorted, fixed it

## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Fixes table format issue

## :green_heart: How did you test it?
checked the format in preview

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by rajadilipkolli** [comment]
Thanks, can you give me pointers. I will take it up.

**Comment by maciejwalkowiak** [comment]
@rajadilipkolli not much more than https://docs.asciidoctor.org/asciidoctor/latest/

**Comment by rajadilipkolli** [comment]
@maciejwalkowiak Are you ok with the auto width now?

**Comment by maciejwalkowiak** [comment]
Still does not look 100% correct but perhaps it's an issue with Asciidoctor itself. I'll merge as it better than it used to be. Thanks @rajadilipkolli !

**Pull request merged**
