### PR TITLE
Support for AWS Aurora cluster

### PR DESCRIPTION
**Pull request by virajkanwade**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Support for AWS Aurora cluster

## :bulb: Motivation and Context

https://github.com/awspring/spring-cloud-aws/issues/322

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by virajkanwade** [comment]
any thoughts on this?

**Comment by maciejwalkowiak** [comment]
@virajkanwade 2.4.x is in maintenance mode and we do not plan to add more features there. Not sure at this moment if anything more except bugfixes will be merged into this branch.

Regarding your PR - if we decide to merge support for aurora clusters tests will have to be added.

**Comment by virajkanwade** [comment]
@maciejwalkowiak ohhk. we were hoping it would be merged in next minor release and we would be able to use it. The AWS advanced JDBC is still far away from being production ready.
Looks like we too will have to go the Vlad's complex route even when a simple solution would have been possible. :(
Anyways thats for your response.

**Comment by maciejwalkowiak** [comment]
@virajkanwade it's been a while, apologies for that. We don't maintain 2.x branch anymore and we dropped JDBC support in 3.0. We may introduce again JDBC module but we need to research first what makes sense considering https://github.com/awslabs/aws-advanced-jdbc-wrapper is there.

**Pull request closed without merging**
