### PR TITLE
Fix timeout handling in QueueMessageChannel

### PR DESCRIPTION
**Pull request by jorgenota**
The timeout parameter of PollableChannel.receive() method represents the timeout in milliseconds (so it should be transformed into seconds when building the ReceiveMessageRequest). Besides, it should use MessageChannel.INDEFINITE_TIMEOUT to represent indefinite timeout (not 0).

## :loudspeaker: Type of change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Minor changes to better handle timeout parameter when receiving messages from an SQS queue.

## :bulb: Motivation and Context

I suggest this fixes to align with PollableChannel interface:
- According to javadoc of PollableChannel, `MessageChannel.INDEFINITE_TIMEOUT` should be used to represent indefinite timeout (instead of 0). Besides, no args `PollableChannel.receive()` method should "block indefinitely if necessary".
- The `timeout` parameter of `PollableChannel.receive(timeout)` method represents the timeout in milliseconds (so it should be transformed into seconds when building the ReceiveMessageRequest).

Fixes issue #122 

## :pencil: Checklist

- [X ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Review by maciejwalkowiak — COMMENTED** [review]
Thanks @jorgenota for the PR. Since the unit changes, we need to consider this as a breaking change. 

According to SQS spec, to achieve long polling, `receiveMessage` should have `waitTimeoutSeconds` set to `0` - which should be the case when `receive` is called with `MessageChannel.INDEFINITE_TIMEOUT`, or am I missing something?

**Comment by jorgenota** [comment]
> According to SQS spec, to achieve long polling, `receiveMessage` should have `waitTimeoutSeconds` set to `0` - which should be the case when `receive` is called with `MessageChannel.INDEFINITE_TIMEOUT`, or am I missing something?

The problem is that, according to the javadoc of `PollableChannel.receive(timeout)` you should use the value `MessageChannel.INDEFINITE_TIMEOUT` (i.e. -1) to set an indefinite timeout. Then, the implementation of `QueueMessageChannel` should translate this (-1) into whatever SQS requires (in this case, a 0).

**Comment by maciejwalkowiak** [comment]
Sorry for late reply.

That makes sense, but I don't see this translation from -1 into 0..? Changing seconds to seconds to millis - good catch - it's a breaking change though, we would have to wait with that likely till 3.0

**Comment by jorgenota** [comment]
Regarding the -1 and 0: the translation is basically between Spring's API and Amazon's API. The first one uses -1 and the latter 0.

**Comment by maciejwalkowiak** [comment]
@jorgenota apologies for a delay. We do not want to introduce breaking changes for versions that use AWS SDK v1. We will keep your change in mind for 3.0. Thanks!

**Pull request closed without merging**
