### PR TITLE
fix: fix upload-docs workflow

### PR DESCRIPTION
**Pull request by mcruzdev**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

This fix the follow action that was failling: https://github.com/awspring/spring-cloud-aws/actions/runs/2541549766

## :green_heart: How did you test it?
I created a repository in my own GitHub and I tested the download and build of `temurin:8.0.332`

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by mcruzdev** [comment]
Hi @maciejwalkowiak,

I fixed the `upload-docs`

**Comment by maciejwalkowiak** [comment]
@mcruzdev for the sake of consistency, `build and upload docs` action should use the same mechanisms as `build` job - use Java from SDKMan. Do you think you'll have time to update this PR?

**Comment by mcruzdev** [comment]
Yes,
@maciejwalkowiak I will!
I can change it :)

**Comment by mcruzdev** [comment]
Hi @maciejwalkowiak,
Do you thin that is it ok? :)

**Pull request merged**
