### PR TITLE
Fix sending message to cross account FIFO SQS queue, fixes gh-938.

### PR DESCRIPTION
**Pull request by ZhongXiLu**
## :loudspeaker: Type of change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Currently, it is not possible to send a message to a cross account FIFO SQS queue due to a bug where AWS does not allow you to access the `ContentDeduplication` queue attribute value of a cross account FIFO SQS queue.

As described in [this comment](https://github.com/awspring/spring-cloud-aws/issues/938#issuecomment-1796988934) and [this comment](https://github.com/awspring/spring-cloud-aws/pull/950#issuecomment-1814353850), I've introduced a new enum `ContentDeduplication` and added this as an option in `SqsTemplateOptions`.

If the value is `ContentDeduplication.AUTO`, then it follows the current implementation and will always retrieve the ContentDeduplication value at runtime. Otherwise, we take the value from the user and will not make an extra request to AWS to resolve this value. Of course, by default, the strategy is `ContentDeduplication.AUTO`.

## :bulb: Motivation and Context
Fixes [this issue](https://github.com/awspring/spring-cloud-aws/issues/938).

## :green_heart: How did you test it?
- Added some unit tests in `SqsTemplateTests`.
- Also manually tested with a real cross account FIFO SQS queue.

## :pencil: Checklist

- [X] I reviewed submitted code
- [X] I added tests to verify changes
- [X] I updated reference documentation to reflect the change
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

**Comment by tomazfernandes** [comment]
Hey @ZhongXiLu , thanks a lot for the PR.

Considering this issue is more of an edge case scenario, I think this configuration would be a better fit for the `SqsContainerOptions` instead of the main API.

What do you think?

**Comment by maciejwalkowiak** [comment]
I agree with @tomazfernandes. Ideally we do not add new methods to `SqsOperations` for such thing.

**Comment by ZhongXiLu** [comment]
@tomazfernandes I'm not too familiar with the code base, but the `SqsContainerOptions` is now only used for the `SqsMessageListenerContainer`, so there is no container for sending messages currently?

**Comment by tomazfernandes** [comment]
> @tomazfernandes I'm not too familiar with the code base, but the `SqsContainerOptions` is now only used for the `SqsMessageListenerContainer`, so there is no container for sending messages currently?

Oh, my bad, I meant SqsTemplateOptio s.

**Comment by ZhongXiLu** [comment]
> > @tomazfernandes I'm not too familiar with the code base, but the `SqsContainerOptions` is now only used for the `SqsMessageListenerContainer`, so there is no container for sending messages currently?
> 
> Oh, my bad, I meant SqsTemplateOptions.

Ah, I thought about that, but you're maybe right that it fits better here with this use case. I'll try to change it. 👍

**Comment by ZhongXiLu** [comment]
@tomazfernandes I've rewritten my implementation, looks indeed better this way.

**Comment by tejashwinisubbanna** [comment]
Hi Team , Can you please let me know when this fixes available to use (in the MVN repo)

**Comment by tomazfernandes** [comment]
@ZhongXiLu, while reviewing your PR I found a bug in the content deduplication logic and had to change a few things.

I used your logic and added you as an author for `SqsTemplate` and the content deduplication logic, but couldn't use your commits directly.

Hope it's ok.

Thanks for the PR and looking forward for more!

Superseded by #987

**Pull request closed without merging**
