### PR TITLE
#101 fix validator beandefinition not being found

### PR DESCRIPTION
**Pull request by MatejNedic**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Fixes bug where validator beanDefinition is not found.
 #101 

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by maciejwalkowiak — APPROVED** [review]

**Comment by maciejwalkowiak** [comment]
@eddumelendez take a look please

**Comment by lewiscog** [comment]
@MatejNedic @maciejwalkowiak @eddumelendez is it possible to work around this? We currently have a number of services blocked by this bug.

**Comment by maciejwalkowiak** [comment]
@lewiscog the fix will be released next week

**Comment by surajaloksinha** [comment]
By when next week?

**Comment by surajaloksinha** [comment]
This week or next week?

**Comment by MatejNedic** [comment]
> This week or next week?

This week

**Comment by maciejwalkowiak** [comment]
@surajaloksinha @lewiscog 2.3.1 has been released.

**Pull request merged**
