### PR TITLE
Fail on startup if sqs queue does not exist

### PR DESCRIPTION
**Pull request by boolivar**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
This PR adds `failOnMissingQueue` property for `SimpleMessageListenerContainer` to fail on application startup if sqs queue is not found.

## :bulb: Motivation and Context
This PR is my proposal for (my) issue #393 

## :green_heart: How did you test it?
Unit tests and local application run that imports local version `2.4.2-SNAPSHOT` of the library:

```java
@SpringBootApplication
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
    
    @SqsListener("nonexistentqueue")
    public void queueListener(String message) {
    }
}
```
```
cloud.aws.sqs.listener.fail-on-missing-queue = true
```

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps
Yes, I'm aware of `spring-cloud-aws v3`, but `spring-integration-aws` uses `SimpleMessageListenerContainer` so this feature should be exposed there as well.

### CODE REVIEW

**Comment by maciejwalkowiak** [comment]
Thanks for the PR!

FYI `spring-integration-aws` will be eventually migrated to 3.0 as well, but I think we should include this change in 2.x and also make sure that it's gets propagated to 3.0

**Review by maciejwalkowiak — APPROVED** [review]
Perhaps we could also add a failure analyzer for that, but even without it, green light from my side.

@MatejNedic @eddumelendez do you want to take a look?

**Review by MatejNedic — APPROVED** [review]
Tnx on PR!

This looks good to me!

**Comment by maciejwalkowiak** [comment]
Thanks for docs @MatejNedic but you flipped the default. By default in `2.4.x` it will be false as it has to stay backward compatible.

**Comment by MatejNedic** [comment]
@maciejwalkowiak oh did not notice that tnx! Will update!

**Comment by jamfor352** [comment]
Hi @maciejwalkowiak - can you confirm if this is in Spring Cloud AWS 3.0.0 under a different property name or function?
I don't seem to be able to find this in `io.awspring.cloud.autoconfigure.sqs.SqsProperties`

**Comment by tomazfernandes** [comment]
Hi @jamfor352, there’s no autoconfiguration property for this behavior in 3.0 - not sure it should but we can look into that.

The default behavior is to create any missing queues.

You can change this behavior in the ContainerOptions: https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-M3/reference/html/index.html#containeroptions-descriptions

Let us know if that works for you, thanks.

**Comment by jamfor352** [comment]
> Hi @jamfor352, there’s no autoconfiguration property for this behavior in 3.0 - not sure it should but we can look into that.
> 
> The default behavior is to create any missing queues.
> 
> You can change this behavior in the ContainerOptions: https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-M3/reference/html/index.html#containeroptions-descriptions
> 
> Let us know if that works for you, thanks.

Thanks for the reply, I'll look into that - having this in Autoconfiguration would be extremely useful, any reason it was removed when it was functioning in 2.4? I couldn't find any documentation explicitly stating its removal or any reasons why, which threw me for a loop.

(For context: A service creating infrastructure is quite often considered a no-no)

**Comment by tomazfernandes** [comment]
The 3.0 version is a major rewrite of the SQS integration - there’s not much code in common with 2.x. So it’s not that it was removed, it was simply not added to this new version. We chose to do this rewrite because there were many design issues with SQS 2.x, and also to take full advantage of the non-blocking capabilities of AWS SDK 2.0.

It’s not uncommon for frameworks to have resource creation by default - I know Kafka does for example. This helps setting up development and test environments.

For a production environment, it’s expected that the application won’t have permission to create resources, so it should fail if a queue is not found regardless of the configuration.

Maybe we can add this disclaimer about the rewrite to the docs, or maybe in migration guide - sorry the lack of this information threw you in for loop.

**Comment by jamfor352** [comment]
Thanks for the explanation @tomazfernandes . 
In our use-case it wouldn't make sense for the autocreation as we rely on SNS -> SQS fanout (which is a common pattern) and presumably there's no auto-configurable way to attach SQS queues to SNS topics? (If there is that would be great!)

**Comment by MatejNedic** [comment]
Hey @jamfor352 , lets move this to [discussions](https://github.com/awspring/spring-cloud-aws/discussions)  on github. There might be other people wanting to see this and it is better to keep this kind of communication there. I am afraid it will be lost here.
We can then open issues depending on inputs from community and so on.

Just to note SNS has a similar implementation as well regarding resolving topicName to arn. Lets move discussion and see what conclusions we come up with! :)

**Pull request merged**
