### PR TITLE
Make getUrl return location of bucket if object is empty or null.

### PR DESCRIPTION
**Pull request by MatejNedic**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Review by maciejwalkowiak — APPROVED** [review]

**Comment by ryanjbaxter** [comment]
@maciejwalkowiak any chance this can go in the 3.0.x branch as well?

**Comment by ryanjbaxter** [comment]
ping @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
@ryanjbaxter no problem we will backport and release new 3.0.x and 3.1.x asap

**Comment by maciejwalkowiak** [comment]
@ryanjbaxter 3.0.5 released

**Pull request merged**
