### PR TITLE
Upgrade Spring Cloud to 4.2.0

### PR DESCRIPTION
**Pull request by abilng**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by MatejNedic** [comment]
Hey @jansauer , thanks on PR.

Please change in main POM 4.2.0-M2 to 4.2.0 as well

**Comment by jansauer** [comment]
> Hey @jansauer , thanks on PR.
> 
> Please change in main POM 4.2.0-M2 to 4.2.0 as well

I'm happy to do that, but I suspect this was a typo and the mention was intended for @abilng 😄

**Comment by MatejNedic** [comment]
Hahaha yes sorry. Idk why Github didnt gave me @abilng when i typed @ and enter.

Sorry about that 😅

**Comment by MatejNedic** [comment]
Hey @abilng , thanks on PR. Much appreciated!

**Review by MatejNedic — APPROVED** [review]

**Pull request merged**
