### PR TITLE
Add Acknowledgement Shutdown Timeout (#631)

### PR DESCRIPTION
**Pull request by tomazfernandes**
See #631

### CODE REVIEW

**Comment by tomazfernandes** [comment]
With this one I think I'm all set code-wise for RC.

After the SqsTemplate is merged I'll add it to the sample.

There are a few more blind spots of test coverage overall than I'd like, but I think it's good enough and I'll work on adding more tests when I have the time.

**Comment by tomazfernandes** [comment]
I've added another commit with an API cleanup for the ContainerOptions. It probably should have been another PR, but I was afraid there would be too many conflicts with this one. The individual commits are preserved though.

**Review by maciejwalkowiak — APPROVED** [review]
Does it need an update in reference docs?

**Comment by tomazfernandes** [comment]
@maciejwalkowiak with this I'm done!

Feel free to merge when you'd like, and let me know if you have any questions.

Looking forward to the RC!

**Pull request merged**
