### PR TITLE
Relax prefix validation rules in Parameter Store and Secrets Manager …

### PR DESCRIPTION
**Pull request by padilo**
Applies PR #303 for 2.3.x, basically it was a cherry-pick and check that tests passes

All credits to Maciej Walkowiak @MatejNedic 

## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by padilo** [comment]
Could be nice if this is approved if you can release a 2.3.5

**Comment by maciejwalkowiak** [comment]
@padilo what's stopping you from using 2.4.x?

**Comment by padilo** [comment]
We are still using Spring Cloud Ilford (2020.0.5), which is compatible with Spring Boot 2.4.x-2.5.x, so we need to use Spring Cloud AWS 2.3.x

**Comment by padilo** [comment]
Thank you, eager to get the release 2.3.5 :)

**Comment by maciejwalkowiak** [comment]
@padilo 2.3.5 released, should appear in Maven soon

https://github.com/awspring/spring-cloud-aws/releases/tag/v2.3.5

**Pull request merged**
