### PR TITLE
fixes #707

### LINKED ISSUE #707: Using `SnsTemplate#sendNotification(topic_name, message, subject)` fails on FIFO topics
**Type**: Bug

**Component**: SNS

**Likely Culprit**: 
https://github.com/awspring/spring-cloud-aws/blob/a09341d15fd163cb6779e168649cce1a3c963f32/spring-cloud-aws-sns/src/main/java/io/awspring/cloud/sns/core/DefaultTopicArnResolver.java#L50

Possible fix:

Check if the topic name ends with `.fifo`. If it does contain `.fifo` we supply that as an attribute.

See: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sns/model/CreateTopicRequest.html#attributes()

```java
CreateTopicRequest.builder().name(topicName).attributes(
                        new HashMap<>(1) {
                            {
                                put("FifoTopic", String.valueOf(topicName.endsWith(".fifo")));
                            }
                        })
.build()

**Describe the bug**

Actual stack trace
```
software.amazon.awssdk.services.sns.model.SnsException: Topic names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long. (Service: Sns, Status Code: 400, Request ID: LCQ0GG1ZI7LS3PO87M0YC9OMQ8WPKTCGIBNJQHALYF1F7HV6X3II)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.sns.DefaultSnsClient.createTopic(DefaultSnsClient.java:723)
	at io.awspring.cloud.sns.core.DefaultTopicArnResolver.resolveTopicArn(DefaultTopicArnResolver.java:50)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.awspring.cloud.sns.core.CachingTopicArnResolver.resolveTopicArn(CachingTopicArnResolver.java:47)
	at io.awspring.cloud.sns.core.SnsTemplate.resolveMessageChannelByTopicName(SnsTemplate.java:140)
	at io.awspring.cloud.sns.core.SnsTemplate.convertAndSend(SnsTemplate.java:106)
	at io.awspring.cloud.sns.core.SnsTemplate.convertAndSend(SnsTemplate.java:94)
	at io.awspring.cloud.sns.core.SnsTemplate.sendNotification(SnsTemplate.java:118)
```

**Sample**
```java
import jakarta.annotation.Resource;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import io.awspring.cloud.sns.core.*;

@SpringApplication
public class BuggyApplication implements CommandLineRunner {
    @Resource SnsTemplate snsTemplate;
    
    public static void main(String args[]) {
        SpringApplication.run(BuggyApplication.class, args);
    }

    @Override
    public void run(String... args) {
        snsTemplate.("fifo_topic.fifo", "test", "whatever");
    } 
}
```

Localstack SNS topic creation:
```bash
SNS_TOPIC_NAME="fifo_topic.fifo" awslocal sns create-topic --name $SNS_TOPIC_NAME --attributes "FifoTopic=true,ContentBasedDeduplication=true"
```

### PR DESCRIPTION
**Pull request by xiurobert**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Fixes #707 based on suggested fix

## :bulb: Motivation and Context

#707 

## :green_heart: How did you test it?
Added a test case

## :pencil: Checklist

- [ ] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by xiurobert** [comment]
Sorry took a bit long to open this, I was busy

**Comment by maciejwalkowiak** [comment]
@xiurobert I pushed some test fixes and refactorings. Also, had to bump Localstack to 1.4.0 for proper handling of FIFO topics. 

Would you like to add your name in `@author` javadocs in the classes you modified?

**Comment by xiurobert** [comment]
Are the tests working? I'm not too bothered about the @author thing.

**Review by MatejNedic — APPROVED** [review]

**Comment by maciejwalkowiak** [comment]
@xiurobert yes after some changes tests are working

**Pull request merged**
