### PR TITLE
Upgrade Localstack to 1.2.0 

### PR DESCRIPTION
**Pull request by rajadilipkolli**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
Increments the local stack version for better integration

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by maciejwalkowiak** [comment]
Thanks.It should be also done for all the integration tests. Would you like to update it too?

**Comment by rajadilipkolli** [comment]
> Thanks.It should be also done for all the integration tests. Would you like to update it too?

Sure I will

**Comment by rajadilipkolli** [comment]
@maciejwalkowiak , Shouldn't we change it to` localstack:localstack` so that always the latest one is pulled instead of changing the version for every increment?

**Comment by maciejwalkowiak** [comment]
@rajadilipkolli not really it's better to rely on exact versions.

**Comment by maciejwalkowiak** [comment]
Tests are failing now though so likely there is something to fix.

**Pull request merged**
