### PR TITLE
Add Cognito authorities mapper

### PR DESCRIPTION
**Pull request by poklakni**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Added new implementation of GrantedAuthoritiesMapper for AWS cognito + spring security integration. The roles are mapped from _cognito:groups_ token claim.

## :bulb: Motivation and Context
https://github.com/awspring/spring-cloud-aws/issues/681

## :green_heart: How did you test it?
unit tests + local integration with my personal project

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by maciejwalkowiak** [comment]
Thank you @poklakni for a PR! We need an integration test here, but I assume you don't have a Localstack PRO license to test against fake Cognito. I'll add the test as soon as I find time.

**Comment by poklakni** [comment]
perhaps I could ship the empty cognito module first so I can work on other cognito features without conflicts

**Comment by maciejwalkowiak** [comment]
All good @poklakni! We will resolve conflicts. Right now we are planning what to include in 3.0 and what to move to 3.1 and Cognito will be included in 3.1, so please be patient with a review.

**Comment by poklakni** [comment]
I think this PR will be no longer required. I discovered a solution that does not require custom authorities mapper
(https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.html)

unless anyone needs this

**Pull request closed without merging**
