### PR TITLE
Abstract ContainerOptions (#598)

### PR DESCRIPTION
**Pull request by tomazfernandes**
Most changes are related to typing, actual changes are in the `ContainerOptions`, `AbstractContainerOptions` and `SqsContainerOptions` classes.

### CODE REVIEW

**Comment by tomazfernandes** [comment]
I'll add the missing javadocs in a future commit.

**Comment by tomazfernandes** [comment]
About the intermittent error we're getting from local stack:
https://github.com/localstack/localstack/issues/7148

**Comment by tomazfernandes** [comment]
I've added the missing javadocs in the `ContainerOptions`, but will do a last review before merging.

**Comment by tomazfernandes** [comment]
I think this is good enough for now, and we can always edit javadocs later.

**Comment by tomazfernandes** [comment]
If anyone would like to review, I'll keep it open. Thanks.

**Comment by maciejwalkowiak** [comment]
I will!

**Comment by tomazfernandes** [comment]
> I will!

Cool, thanks!

**Review by maciejwalkowiak — APPROVED** [review]
It looks good but why do we actually need this separation to `AbstractContainerOptions` and `SqsContainerOptions`?

**Comment by tomazfernandes** [comment]
This is to keep it in sync with the rest of the architecture.

The way it was, the abstract classes for the listener would depend on ContainerOptions, which in turn had hard dependencies on SQS SDK classes.

This way, ContainerOptions and AbstractContainerOptions have no dependencies to SQS, like the rest of the architecture.

**Pull request merged**
