### PR TITLE
Updates spring cloud build/commons to 3.1.0

### PR DESCRIPTION
**Pull request by spencergibb**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring

## :scroll: Description

Updates to spring cloud 2021.0.0 and boot 2.6.x

## :green_heart: How did you test it?

Ran a full build

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by spencergibb** [comment]
Would need a new 2.4.x branch

**Comment by maciejwalkowiak** [comment]
Thanks @spencergibb. We will release 2.4 with this change in upcoming days.

**Review by maciejwalkowiak — APPROVED** [review]
Should be merged to 2.4.x branch (once created).

**Comment by sreekanth-tf** [comment]
Thank you @maciejwalkowiak :+1:

**Comment by sfussenegger** [comment]
@maciejwalkowiak is there an ETA for a 2.4 release? Would it be possible to release a milestone or release candidate now?

**Comment by maciejwalkowiak** [comment]
@sfussenegger it will happen most likely over the weekend or beginning of next week - we are having team meeting today in the afternoon to discuss it.

**Pull request merged**
